import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :parentcontrolswin, ParentcontrolswinWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  check_origin: [
      "http://parentcontrols.win", 
      "https://parentcontrols.win",
      "http://www.parentcontrols.win", 
      "https://www.parentcontrols.win",
      "https://parentcontrolswin.gigalixirapp.com/",
      "parentcontrols.win.gigalixirdns.com",
      "www.parentcontrols.win.gigalixirdns.com" # all of check_origin may be unnecessary 
  ]
  
config :parentcontrolswin, base_url: "https://www.parentcontrols.win"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Parentcontrolswin.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

# Stripe API keys 
stripe_api_key = System.get_env("STRIPE_API_SECRET") ||
    raise """
    environment variable STRIPE_API_KEY is missing.
    You can obtain it from the stripe dashboard: https://dashboard.stripe.com/test/apikeys
    """

stripe_webhook_key = System.get_env("STRIPE_WEBHOOK_SIGNING_SECRET") ||
    raise """
    environment variable STRIPE_WEBHOOK_SIGNING_SECRET is missing.
    You can obtain it from the stripe dashboard: https://dashboard.stripe.com/account/webhooks
    """

config :stripity_stripe,
  api_key: stripe_api_key,
  signing_secret: stripe_webhook_key,
  stripe_price_id: "price_1PhHFnDrVDu5S9fVaqyDj45s",
  stripe_coupon_id: "U3U0MXwB"

# Google Recaptcha API keys, indentical for dev and prod
recaptcha_public_key = System.get_env("RECAPTCHA_PUBLIC_KEY") ||
    raise """
    environment variable RECAPTCHA_PUBLIC_KEY is missing.
    """

recaptcha_private_key = System.get_env("RECAPTCHA_PRIVATE_KEY") ||
    raise """
    environment variable RECAPTCHA_PRIVATE_KEY is missing.
    """

config :recaptcha,
  public_key: recaptcha_public_key,
  secret: recaptcha_private_key